version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Volumen persistente para configuración de Jenkins
      - jenkins_home:/var/jenkins_home

      # Monta el socket de Docker para que Jenkins pueda usar Docker del host
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
