Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "ubuntu-vagrant"
  config.vm.network "private_network", ip: "192.168.56.10"

  # Sincroniza la carpeta correcta con el playbook
  config.vm.synced_folder "../Ansible", "/vagrant/ansible", type: "virtualbox"

  # Instala Ansible en la VM automáticamente
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y ansible
  SHELL

  # Ejecuta automáticamente el playbook desde la carpeta compartida
  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.playbook = "/vagrant/ansible/playbook.yml"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
end
